DROP DATABASE IF EXISTS philhumans;

CREATE DATABASE IF NOT EXISTS philhumans;

CREATE TABLE IF NOT EXISTS philhumans.user(
    name VARCHAR(50) PRIMARY KEY,
	low_numeracy BOOL NOT NULL DEFAULT TRUE,
	consequences BOOL NOT NULL DEFAULT TRUE,
	report_day TINYINT UNSIGNED CHECK (report_day < 7) NOT NULL DEFAULT 0,
	report_hour TINYINT UNSIGNED CHECK (report_hour < 24) NOT NULL DEFAULT 0,
	threshold TINYINT UNSIGNED CHECK (threshold IN (0, 5, 10)) NOT NULL DEFAULT 10,
	energy_report BOOL NOT NULL DEFAULT TRUE,
    carbohydrate_report BOOL NOT NULL DEFAULT TRUE, /*ADDED*/
	fat_report BOOL NOT NULL DEFAULT TRUE,
	s_report BOOL NOT NULL DEFAULT TRUE,
	sugar_report BOOL NOT NULL DEFAULT TRUE,
	protein_report BOOL NOT NULL DEFAULT TRUE,
	sodium_report BOOL NOT NULL DEFAULT TRUE,
	energy_unit VARCHAR(10) CHECK (energy_unit IN ('calories', 'kilojoules')) NOT NULL,
	meal_name0 VARCHAR(50) NOT NULL,
	meal_name1 VARCHAR(50),
	meal_name2 VARCHAR(50),
	meal_name3 VARCHAR(50),
	meal_name4 VARCHAR(50),
	meal_name5 VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS philhumans.authorised_users(
    telegram_user VARCHAR(50) PRIMARY KEY,
	mfp_user VARCHAR(50),
	first_name VARCHAR(50),
	sender_id VARCHAR(36),
	group_num TINYINT UNSIGNED CHECK (group_num IN (1, 2, 3)),
	timezone VARCHAR(10) CHECK (timezone IN ('EDT', 'CEST', 'IST', 'AEST')) NOT NULL DEFAULT 'CEST'
);

CREATE TABLE IF NOT EXISTS philhumans.day(
	user VARCHAR(50),
	id DATE,
	energy_goal SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	fat_goal SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	carbohydrates_goal SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	sugar_goal SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	protein_goal SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	sodium_goal SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	total_energy SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	total_fat SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	total_carbohydrates SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	total_sugar SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	total_protein SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	total_sodium SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(user, id),
	FOREIGN KEY(user) REFERENCES philhumans.user(name) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS philhumans.meal(
	user VARCHAR(50),
	day DATE,
	id TINYINT UNSIGNED CHECK (id < 6),
	energy SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	fat SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	carbohydrates SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	sugar SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	protein SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	sodium SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(user, day, id),
	FOREIGN KEY(user) REFERENCES philhumans.user(name) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(user, day) REFERENCES philhumans.day(user, id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS philhumans.food(
	user VARCHAR(50),
	day DATE,
	meal TINYINT UNSIGNED,
	id TINYINT UNSIGNED,
	name VARCHAR(300) NOT NULL,
	unit VARCHAR(25) NOT NULL,
	quantity FLOAT CHECK (quantity >= 0) NOT NULL DEFAULT 0,
	energy SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	fat SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	carbohydrates SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	sugar SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	protein SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	sodium SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(user, day, meal, id),
	FOREIGN KEY(user) REFERENCES philhumans.user(name) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(user, day) REFERENCES philhumans.day(user, id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(user, day, meal) REFERENCES philhumans.meal(user, day, id) ON DELETE CASCADE ON UPDATE CASCADE
);
